name: Build

on:
  push:
    branches: ['master']
  pull_request:

permissions:
  contents: read

env:
  GHIDRA_DOWNLOAD_URL: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.4_build/ghidra_10.4_PUBLIC_20230928.zip
  GHIDRA_INSTALL_NAME: ghidra_10.4_PUBLIC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      # This is better than just running ./gradlew for reasons
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Download and Extract Ghidra
        run: |
          cd "$RUNNER_TEMP"
          curl -L "$GHIDRA_DOWNLOAD_URL" -o ghidra.zip
          unzip -q ghidra.zip
      - name: Run Gradle
        run: ./gradlew
        env: 
          GHIDRA_INSTALL_DIR: ${{ runner.temp }}/${{ env.GHIDRA_INSTALL_NAME }}
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.zip
          name: Ghidra-SuperMonkeyBallTools
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/*.zip
          draft: true