name: Build

on:
  push:
    branches: ["master"]
    tags: ["*"]
  pull_request:

permissions:
  contents: write

env:
  GHIDRA_DOWNLOAD_URL: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_11.4.2_build/ghidra_11.4.2_PUBLIC_20250826.zip
  GHIDRA_INSTALL_NAME: ghidra_11.4.2_PUBLIC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Download and Extract Ghidra
        run: |
          cd "$RUNNER_TEMP"
          curl -L "$GHIDRA_DOWNLOAD_URL" -o ghidra.zip
          unzip -q ghidra.zip
      # This is better than just running ./gradlew for reasons
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run Gradle
        run: ./gradlew
        env:
          GHIDRA_INSTALL_DIR: ${{ runner.temp }}/${{ env.GHIDRA_INSTALL_NAME }}
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.zip
          name: SuperMonkeyBallTools
      - name: Rename Release Asset
        if: github.ref_type == 'tag'
        run: mv dist/*.zip dist/SuperMonkeyBallTools-${GITHUB_REF_NAME}-${GHIDRA_INSTALL_NAME}.zip
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./dist/*.zip
          draft: true
